
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

hacs:


shell_command:
    fetch_schedule: "python3 /config/fetch_schedule.py {{ states('input_text.selected_schedule_date') }}"

input_text:
    schedule_data:
        name: Schedule Data
        max: 10000
        
template:
    - sensor:
        - name: "current_date"
          state: "{{ now().date() }}"
